# Generated by Django 4.1.13 on 2024-01-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
