# Generated by Django 5.0.1 on 2024-01-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_create_at_blog_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
