# Generated by Django 5.0.1 on 2024-01-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_blog_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
