# Generated by Django 5.0.1 on 2024-01-09 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
