# Generated by Django 5.0.1 on 2024-01-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
